<a href="https://colab.research.google.com/github/AnnamNarasimha2003/Tyson/blob/main/Copy_of_Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [ ]:
#load the csv file
df= pd.read_csv('/Food Nutrition.csv')
#print the loaded data
print(df)

              Timestamp                              FOOD_ITEM  \
0    7/10/2024 19:25:10                                   figs
1    7/10/2024 19:27:36                              Currants
2    7/10/2024 19:35:23                               Chicken
3    7/10/2024 19:39:30                          Goji Berries
4    7/10/2024 19:40:16                               Coconut
..                  ...                                    ...
295  7/16/2024 23:08:25     Egg white omelette with vegetables
296  7/16/2024 23:10:33                  Quinoa breakfast bowl
297  7/16/2024 23:13:25          Cottage Cheese with Pineapple
298  7/16/2024 23:19:56  Whole Grain Pancakes with Fresh Fruit
299  7/16/2024 23:24:02         Smoked Salmon and Avocado Wrap

            FOOD_GROUP SERVING_SIZE (in g) CALORIC_VALUE (in g)  \
0    Dry fruits, Seeds                  50                  249
1    Dry fruits, Seeds                  50                  283
2                 Meat                 100                  239
3    Dry fruits, Seeds                  80                  349
4    Dry fruits, Seeds                  80                  660
..                 ...                 ...                  ...
295              Meals                 298                  350
296              Meals                 316                  396
297              Meals                 150                  150
298              Meals                 150                  250
299              Meals                  80                  400

    PROTEIN (in g)  FAT (in g)  SATURATED_FAT (in g)  \
0              3.3         0.9                   NaN
1              3.8         0.4                   NaN
2               27        14.0                   3.8
3             14.3         0.4                   NaN
4              6.9        64.5                   NaN
..             ...         ...                   ...
295             28        13.6                   3.3
296             20        12.0                   NaN
297             14         5.0                   3.5
298              8         5.0                   1.0
299             30        20.0                   5.0

    MONOUNSATURATED_FAT (in g) POLYUNSATURATED_FAT (in g)  ... WATER (in g)  \
0                          NaN                        NaN  ...          NaN
1                          NaN                        NaN  ...          NaN
2                          NaN                        NaN  ...          NaN
3                          NaN                        NaN  ...          NaN
4                          NaN                        NaN  ...          NaN
..                         ...                        ...  ...          ...
295                        7.9                        1.4  ...            0
296                        NaN                        NaN  ...          NaN
297                        NaN                        NaN  ...          NaN
298                        NaN                        NaN  ...          NaN
299                         10                          5  ...          NaN

     CALCIUM (in mg)  COPPER (in mg)  IRON (in mg)  MAGNESIUM (in mg)  \
0                NaN             NaN           NaN                NaN
1                NaN             NaN           NaN                NaN
2                1.0             NaN           7.0                5.0
3                NaN             NaN           NaN                NaN
4                NaN             NaN           NaN                NaN
..               ...             ...           ...                ...
295            148.9             0.2           0.7               29.9
296              NaN             NaN           NaN                NaN
297              NaN             NaN           NaN                NaN
298            150.0             0.2           2.7               60.0
299            100.0             0.2           1.8               40.0

    MANGANESE (in mg) PHOSPHORUS (in mg) POTASSIUM (in mg) SELENIUM (in mg)  \
0                 NaN                NaN               NaN              NaN
1                 NaN                NaN               NaN              NaN
2                 NaN                NaN             223.0              NaN
3                 NaN                NaN               NaN              NaN
4                 NaN                NaN               NaN              NaN
..                ...                ...               ...              ...
295               NaN              148.1             455.9             33.4
296               NaN                NaN             324.0              NaN
297               NaN                NaN               0.3              NaN
298               NaN                210             210.0              8.3
299               NaN                140             350.0                7

    ZINC (in mg)
0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
..           ...
295          0.9
296          NaN
297          NaN
298          0.6
299          1.5

[300 rows x 37 columns]

In [ ]:
#information
df.info()
#print column names
df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 37 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Timestamp                   300 non-null    object
 1   FOOD_ITEM                   300 non-null    object
 2   FOOD_GROUP                  300 non-null    object
 3   SERVING_SIZE (in g)         300 non-null    object
 4   CALORIC_VALUE (in g)        300 non-null    object
 5   PROTEIN (in g)              300 non-null    object
 6   FAT (in g)                  300 non-null    float64
 7   SATURATED_FAT (in g)        273 non-null    float64
 8   MONOUNSATURATED_FAT (in g)  270 non-null    object
 9   POLYUNSATURATED_FAT (in g)  268 non-null    object
 10  CARBOHYDRATES (in g)        299 non-null    object
 11  DIETARY_FIBER (in g)        297 non-null    float64
 12  SUGARS (in g)               273 non-null    float64
 13  SODIUM (in g)               272 non-null    float64
 14  CHOLESTROL (in mg)          270 non-null    float64
 15  VITAMIN A (in %)            270 non-null    object
 16  VITAMIN B1 (in %)           269 non-null    object
 17  VITAMIN B2 (in %)           268 non-null    object
 18  VITAMIN B3 (in %)           268 non-null    object
 19  VITAMIN B5 (in %)           266 non-null    object
 20  VITAMIN B6 (in %)           268 non-null    object
 21  VITAMIN B11 (in %)          265 non-null    object
 22  VITAMIN B12 (in %)          269 non-null    object
 23  VITAMIN C (in %)            271 non-null    float64
 24  VITAMIN D (in %)            269 non-null    float64
 25  VITAMIN E (in %)            270 non-null    object
 26  VITAMIN K (in %)            269 non-null    object
 27  WATER (in g)                257 non-null    object
 28  CALCIUM (in mg)             271 non-null    float64
 29  COPPER (in mg)              267 non-null    float64
 30  IRON (in mg)                289 non-null    float64
 31  MAGNESIUM (in mg)           282 non-null    float64
 32  MANGANESE (in mg)           264 non-null    object
 33  PHOSPHORUS (in mg)          268 non-null    object
 34  POTASSIUM (in mg)           272 non-null    float64
 35  SELENIUM (in mg)            269 non-null    object
 36  ZINC (in mg)                285 non-null    object
dtypes: float64(13), object(24)
memory usage: 86.8+ KB

Index(['Timestamp', 'FOOD_ITEM', 'FOOD_GROUP', 'SERVING_SIZE (in g)',
       'CALORIC_VALUE (in g)', 'PROTEIN (in g)', 'FAT (in g)',
       'SATURATED_FAT (in g)', 'MONOUNSATURATED_FAT (in g)',
       'POLYUNSATURATED_FAT (in g)', 'CARBOHYDRATES (in g)',
       'DIETARY_FIBER (in g)', 'SUGARS (in g)', 'SODIUM (in g)',
       'CHOLESTROL (in mg)', 'VITAMIN A (in %)', 'VITAMIN B1 (in %)',
       'VITAMIN B2 (in %)', 'VITAMIN B3 (in %)', 'VITAMIN B5 (in %)',
       'VITAMIN B6 (in %)', 'VITAMIN B11 (in %)', 'VITAMIN B12 (in %)',
       'VITAMIN C (in %)', 'VITAMIN D (in %)', 'VITAMIN E (in %)',
       'VITAMIN K (in %)', 'WATER (in g)', 'CALCIUM (in mg)', 'COPPER (in mg)',
       'IRON (in mg)', 'MAGNESIUM (in mg)', 'MANGANESE (in mg)',
       'PHOSPHORUS (in mg)', 'POTASSIUM (in mg)', 'SELENIUM (in mg)',
       'ZINC (in mg)'],
      dtype='object')

In [ ]:
#total rows and columns
df.shape

(300, 37)

In [ ]:
#first 5 rows
df.head()

,Timestamp,FOOD_ITEM,FOOD_GROUP,SERVING_SIZE (in g),CALORIC_VALUE (in g),PROTEIN (in g),FAT (in g),SATURATED_FAT (in g),MONOUNSATURATED_FAT (in g),POLYUNSATURATED_FAT (in g),...,WATER (in g),CALCIUM (in mg),COPPER (in mg),IRON (in mg),MAGNESIUM (in mg),MANGANESE (in mg),PHOSPHORUS (in mg),POTASSIUM (in mg),SELENIUM (in mg),ZINC (in mg)
0,7/10/2024 19:25:10,figs,"Dry fruits, Seeds",50,249,3.3,0.9,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7/10/2024 19:27:36,Currants,"Dry fruits, Seeds",50,283,3.8,0.4,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7/10/2024 19:35:23,Chicken,Meat,100,239,27,14.0,3.8,NaN,NaN,...,NaN,1.0,NaN,7.0,5.0,NaN,NaN,223.0,NaN,NaN
3,7/10/2024 19:39:30,Goji Berries,"Dry fruits, Seeds",80,349,14.3,0.4,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7/10/2024 19:40:16,Coconut,"Dry fruits, Seeds",80,660,6.9,64.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Deleting Timestamp column
df=df.drop(columns=['Timestamp'])

In [ ]:
#Descriptive Statistics
df.describe()

,FAT (in g),SATURATED_FAT (in g),DIETARY_FIBER (in g),SUGARS (in g),SODIUM (in g),CHOLESTROL (in mg),VITAMIN C (in %),VITAMIN D (in %),CALCIUM (in mg),COPPER (in mg),IRON (in mg),MAGNESIUM (in mg),POTASSIUM (in mg)
count,300.000000,273.000000,297.000000,273.000000,272.000000,270.000000,271.000000,269.000000,271.000000,267.000000,289.000000,282.000000,272.000000
mean,7.797913,1.753073,3.453670,45.347912,59.846559,15.620704,19.350590,1.348327,355.778819,46.604532,383.264394,498.093773,253.747479
std,11.627205,2.680646,5.408991,616.987914,182.326391,44.273653,35.748646,4.752789,1121.240213,532.103417,1650.985525,2017.592890,265.131770
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.200000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.100000,0.000000,0.300000
50%,1.450000,0.500000,2.000000,3.000000,0.120000,0.000000,2.000000,0.000000,30.000000,0.050000,0.800000,14.400000,217.000000
75%,12.475000,2.300000,5.000000,10.000000,10.700000,0.000000,21.500000,0.000000,150.000000,0.200000,3.200000,67.250000,400.000000
max,65.200000,18.000000,53.200000,10200.000000,1600.000000,373.000000,240.000000,50.000000,9240.000000,6160.000000,15000.000000,19800.000000,1375.000000

In [ ]:
#Convert into uppercase
df1=df.applymap(lambda x:x.upper() if isinstance(x,str) else x)
print(df1)

                                 FOOD_ITEM         FOOD_GROUP  \
0                                     FIGS  DRY FRUITS, SEEDS
1                                CURRANTS   DRY FRUITS, SEEDS
2                                 CHICKEN                MEAT
3                            GOJI BERRIES   DRY FRUITS, SEEDS
4                                 COCONUT   DRY FRUITS, SEEDS
..                                     ...                ...
295     EGG WHITE OMELETTE WITH VEGETABLES              MEALS
296                  QUINOA BREAKFAST BOWL              MEALS
297          COTTAGE CHEESE WITH PINEAPPLE              MEALS
298  WHOLE GRAIN PANCAKES WITH FRESH FRUIT              MEALS
299         SMOKED SALMON AND AVOCADO WRAP              MEALS

    SERVING_SIZE (in g) CALORIC_VALUE (in g) PROTEIN (in g)  FAT (in g)  \
0                    50                  249            3.3         0.9
1                    50                  283            3.8         0.4
2                   100                  239             27        14.0
3                    80                  349           14.3         0.4
4                    80                  660            6.9        64.5
..                  ...                  ...            ...         ...
295                 298                  350             28        13.6
296                 316                  396             20        12.0
297                 150                  150             14         5.0
298                 150                  250              8         5.0
299                  80                  400             30        20.0

     SATURATED_FAT (in g) MONOUNSATURATED_FAT (in g)  \
0                     NaN                        NaN
1                     NaN                        NaN
2                     3.8                        NaN
3                     NaN                        NaN
4                     NaN                        NaN
..                    ...                        ...
295                   3.3                        7.9
296                   NaN                        NaN
297                   3.5                        NaN
298                   1.0                        NaN
299                   5.0                         10

    POLYUNSATURATED_FAT (in g) CARBOHYDRATES (in g)  ...  WATER (in g)  \
0                          NaN                 63.9  ...           NaN
1                          NaN                 69.2  ...           NaN
2                          NaN                    0  ...           NaN
3                          NaN                 69.7  ...           NaN
4                          NaN                 23.7  ...           NaN
..                         ...                  ...  ...           ...
295                        1.4                  7.6  ...             0
296                        NaN                   62  ...           NaN
297                        NaN                   12  ...           NaN
298                        NaN                   45  ...           NaN
299                          5                   40  ...           NaN

     CALCIUM (in mg)  COPPER (in mg)  IRON (in mg) MAGNESIUM (in mg)  \
0                NaN             NaN           NaN               NaN
1                NaN             NaN           NaN               NaN
2                1.0             NaN           7.0               5.0
3                NaN             NaN           NaN               NaN
4                NaN             NaN           NaN               NaN
..               ...             ...           ...               ...
295            148.9             0.2           0.7              29.9
296              NaN             NaN           NaN               NaN
297              NaN             NaN           NaN               NaN
298            150.0             0.2           2.7              60.0
299            100.0             0.2           1.8              40.0

    MANGANESE (in mg) PHOSPHORUS (in mg) POTASSIUM (in mg) SELENIUM (in mg)  \
0                 NaN                NaN               NaN              NaN
1                 NaN                NaN               NaN              NaN
2                 NaN                NaN             223.0              NaN
3                 NaN                NaN               NaN              NaN
4                 NaN                NaN               NaN              NaN
..                ...                ...               ...              ...
295               NaN              148.1             455.9             33.4
296               NaN                NaN             324.0              NaN
297               NaN                NaN               0.3              NaN
298               NaN                210             210.0              8.3
299               NaN                140             350.0                7

    ZINC (in mg)
0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
..           ...
295          0.9
296          NaN
297          NaN
298          0.6
299          1.5

[300 rows x 36 columns]

In [ ]:
#extract milliliters values into a new column 'SERVING_SIZE (in ml)'
df1['SERVING_SIZE (in ml)']=df1['SERVING_SIZE (in g)'].str.extract(r'(\d+\s*ML)',expand=False)
df1.fillna(0,inplace=True)
print(df1.head(25))

                 FOOD_ITEM         FOOD_GROUP SERVING_SIZE (in g)  \
0                     FIGS  DRY FRUITS, SEEDS                  50
1                CURRANTS   DRY FRUITS, SEEDS                  50
2                 CHICKEN                MEAT                 100
3            GOJI BERRIES   DRY FRUITS, SEEDS                  80
4                 COCONUT   DRY FRUITS, SEEDS                  80
5   DATES (MEDJOOL, DRIED)  DRY FRUITS, SEEDS                  50
6                  MUTTON                MEAT                 100
7                OLIVE OIL               OILS                  14
8              COCONUT OIL               OILS                  14
9               CANOLA OIL               OILS                  14
10                   APPLE             FRUITS                 182
11                  BANANA             FRUITS                 100
12           SUNFLOWER OIL               OILS                  14
13              WATERMELON             FRUITS                 154
14             SOYBEAN OIL               OILS                  14
15              STRAWBERRY             FRUITS                  72
16                    PEAR             FRUITS                 178
17                   PEACH             FRUITS                 175
18                  PAPAYA             FRUITS                 152
19                   MANGO             FRUITS                 100
20             AVOCADO OIL               OILS                  14
21               ASH GOURD         VEGETABLES                 100
22            BLACK COFFEE          BEVERAGES              240 ML
23               BLACK TEA          BEVERAGES               240ML
24           COFFEE OR TEA          BEVERAGES                15ML

   CALORIC_VALUE (in g) PROTEIN (in g)  FAT (in g)  SATURATED_FAT (in g)  \
0                   249            3.3         0.9                   0.0
1                   283            3.8         0.4                   0.0
2                   239             27        14.0                   3.8
3                   349           14.3         0.4                   0.0
4                   660            6.9        64.5                   0.0
5                   299            3.1         0.5                   0.0
6                   143             26         3.5                   1.2
7                   119              0        14.0                   2.0
8                   121              0        13.5                  11.2
9                   124              0        14.0                   1.0
10                   95              0         0.0                   0.0
11                   89            1.1         0.3                   0.1
12                  120              0        14.0                   1.5
13                   46              1         0.0                   0.0
14                  120              0        14.0                   2.0
15                   25              0         0.0                   0.0
16                  103              1         0.0                   0.0
17                   68              2         0.0                   0.0
18                   60              1         0.0                   0.0
19                   65            0.5         0.3                   0.0
20                  124              0        14.0                   2.0
21                  340             24         2.0                   0.0
22                    2            0.3         0.0                   0.0
23                    2              0         0.0                   0.0
24                    9            0.5         0.5                   0.3

   MONOUNSATURATED_FAT (in g) POLYUNSATURATED_FAT (in g) CARBOHYDRATES (in g)  \
0                           0                          0                 63.9
1                           0                          0                 69.2
2                           0                          0                    0
3                           0                          0                 69.7
4                           0                          0                 23.7
5                           0                          0                 79.2
6                           -                          -                    0
7                          10                        1.2                    0
8                         0.8                        0.2                    0
9                           9                          4                    0
10                          0                          0                   25
11                          0                          0                   23
12                        2.7                        9.4                    0
13                          0                          0                   12
14                          3                          8                    0
15                          0                          0                    6
16                          0                          0                   28
17                          0                          0                   17
18                          0                          0                   15
19                          0                          0                   17
20                         10                          2                    0
21                          -                          -                   60
22                          0                          0                    0
23                          0                          0                  0.7
24                          0                          0                  0.7

    ...  CALCIUM (in mg)  COPPER (in mg)  IRON (in mg)  MAGNESIUM (in mg)  \
0   ...             0.00           0.000          0.00               0.00
1   ...             0.00           0.000          0.00               0.00
2   ...             1.00           0.000          7.00               5.00
3   ...             0.00           0.000          0.00               0.00
4   ...             0.00           0.000          0.00               0.00
5   ...             0.00           0.000          0.00               0.00
6   ...             0.00           0.000          6.00               7.00
7   ...             1.00           0.000          0.10               0.00
8   ...             0.00           0.000          0.10               0.00
9   ...             0.00           0.000          0.10               0.00
10  ...          1820.00           0.000          0.00               0.00
11  ...             0.00           0.000       1000.00            6000.00
12  ...             0.00           0.000          0.10               0.00
13  ...          1540.00           0.000       3080.00               0.00
14  ...             0.00           0.000          0.10               0.00
15  ...             0.00           0.000          0.00               0.00
16  ...          3560.00           0.000       3560.00               0.00
17  ...          1750.00           0.000       3500.00               0.00
18  ...            29.00           0.000          0.36               0.00
19  ...            18.20           0.100          0.26               0.00
20  ...             0.02           0.030          0.10               0.09
21  ...            85.00           1.059          9.95             333.00
22  ...             4.70           0.000          0.00               0.00
23  ...             7.00           0.000          0.00               0.00
24  ...            17.00           0.000          0.00               0.00

   MANGANESE (in mg) PHOSPHORUS (in mg) POTASSIUM (in mg) SELENIUM (in mg)  \
0                  0                  0               0.0                0
1                  0                  0               0.0                0
2                  0                  0             223.0                0
3                  0                  0               0.0                0
4                  0                  0               0.0                0
5                  0                  0               0.0                0
6                  -                  -             421.0                -
7                  0                  0               0.0                0
8                  0                  0               0.0                0
9                  0                  0               0.0                0
10                 0                  0               0.0                0
11                 0                  0             358.0                0
12                 0                  0               0.0                0
13                 0                  0               0.0                0
14                 0                  0               0.0                0
15                 0                  0               0.0                0
16                 0                  0               0.0                0
17                 0                  0               0.0                0
18                 0               14.5             263.9                0
19                 0               23.1             156.0                0
20             0.001                0.2               0.5             0.02
21             1.544                438            1375.0           0.0091
22                 0                  0             116.0                0
23                 0                  0              87.0                0
24                 0                  0               0.0                0

   ZINC (in mg) SERVING_SIZE (in ml)
0             0                    0
1             0                    0
2             0                    0
3             0                    0
4             0                    0
5             0                    0
6             -                    0
7             0                    0
8             0                    0
9             0                    0
10            0                    0
11            0                    0
12            0                    0
13            0                    0
14            0                    0
15            0                    0
16            0                    0
17            0                    0
18            0                    0
19            0                    0
20            0                    0
21         6.11                    0
22            0               240 ML
23            0                240ML
24            0                 15ML

[25 rows x 37 columns]

In [ ]:
#convert ml values in SERVING_SIZE (in g) column to NaN
df1['SERVING_SIZE (in g)']=pd.to_numeric(df1['SERVING_SIZE (in g)'],errors='coerce')
print(df1.head(25))

                 FOOD_ITEM         FOOD_GROUP  SERVING_SIZE (in g)  \
0                     FIGS  DRY FRUITS, SEEDS                 50.0
1                CURRANTS   DRY FRUITS, SEEDS                 50.0
2                 CHICKEN                MEAT                100.0
3            GOJI BERRIES   DRY FRUITS, SEEDS                 80.0
4                 COCONUT   DRY FRUITS, SEEDS                 80.0
5   DATES (MEDJOOL, DRIED)  DRY FRUITS, SEEDS                 50.0
6                  MUTTON                MEAT                100.0
7                OLIVE OIL               OILS                 14.0
8              COCONUT OIL               OILS                 14.0
9               CANOLA OIL               OILS                 14.0
10                   APPLE             FRUITS                182.0
11                  BANANA             FRUITS                100.0
12           SUNFLOWER OIL               OILS                 14.0
13              WATERMELON             FRUITS                154.0
14             SOYBEAN OIL               OILS                 14.0
15              STRAWBERRY             FRUITS                 72.0
16                    PEAR             FRUITS                178.0
17                   PEACH             FRUITS                175.0
18                  PAPAYA             FRUITS                152.0
19                   MANGO             FRUITS                100.0
20             AVOCADO OIL               OILS                 14.0
21               ASH GOURD         VEGETABLES                100.0
22            BLACK COFFEE          BEVERAGES                  NaN
23               BLACK TEA          BEVERAGES                  NaN
24           COFFEE OR TEA          BEVERAGES                  NaN

   CALORIC_VALUE (in g) PROTEIN (in g)  FAT (in g)  SATURATED_FAT (in g)  \
0                   249            3.3         0.9                   0.0
1                   283            3.8         0.4                   0.0
2                   239             27        14.0                   3.8
3                   349           14.3         0.4                   0.0
4                   660            6.9        64.5                   0.0
5                   299            3.1         0.5                   0.0
6                   143             26         3.5                   1.2
7                   119              0        14.0                   2.0
8                   121              0        13.5                  11.2
9                   124              0        14.0                   1.0
10                   95              0         0.0                   0.0
11                   89            1.1         0.3                   0.1
12                  120              0        14.0                   1.5
13                   46              1         0.0                   0.0
14                  120              0        14.0                   2.0
15                   25              0         0.0                   0.0
16                  103              1         0.0                   0.0
17                   68              2         0.0                   0.0
18                   60              1         0.0                   0.0
19                   65            0.5         0.3                   0.0
20                  124              0        14.0                   2.0
21                  340             24         2.0                   0.0
22                    2            0.3         0.0                   0.0
23                    2              0         0.0                   0.0
24                    9            0.5         0.5                   0.3

   MONOUNSATURATED_FAT (in g) POLYUNSATURATED_FAT (in g) CARBOHYDRATES (in g)  \
0                           0                          0                 63.9
1                           0                          0                 69.2
2                           0                          0                    0
3                           0                          0                 69.7
4                           0                          0                 23.7
5                           0                          0                 79.2
6                           -                          -                    0
7                          10                        1.2                    0
8                         0.8                        0.2                    0
9                           9                          4                    0
10                          0                          0                   25
11                          0                          0                   23
12                        2.7                        9.4                    0
13                          0                          0                   12
14                          3                          8                    0
15                          0                          0                    6
16                          0                          0                   28
17                          0                          0                   17
18                          0                          0                   15
19                          0                          0                   17
20                         10                          2                    0
21                          -                          -                   60
22                          0                          0                    0
23                          0                          0                  0.7
24                          0                          0                  0.7

    ...  CALCIUM (in mg)  COPPER (in mg)  IRON (in mg)  MAGNESIUM (in mg)  \
0   ...             0.00           0.000          0.00               0.00
1   ...             0.00           0.000          0.00               0.00
2   ...             1.00           0.000          7.00               5.00
3   ...             0.00           0.000          0.00               0.00
4   ...             0.00           0.000          0.00               0.00
5   ...             0.00           0.000          0.00               0.00
6   ...             0.00           0.000          6.00               7.00
7   ...             1.00           0.000          0.10               0.00
8   ...             0.00           0.000          0.10               0.00
9   ...             0.00           0.000          0.10               0.00
10  ...          1820.00           0.000          0.00               0.00
11  ...             0.00           0.000       1000.00            6000.00
12  ...             0.00           0.000          0.10               0.00
13  ...          1540.00           0.000       3080.00               0.00
14  ...             0.00           0.000          0.10               0.00
15  ...             0.00           0.000          0.00               0.00
16  ...          3560.00           0.000       3560.00               0.00
17  ...          1750.00           0.000       3500.00               0.00
18  ...            29.00           0.000          0.36               0.00
19  ...            18.20           0.100          0.26               0.00
20  ...             0.02           0.030          0.10               0.09
21  ...            85.00           1.059          9.95             333.00
22  ...             4.70           0.000          0.00               0.00
23  ...             7.00           0.000          0.00               0.00
24  ...            17.00           0.000          0.00               0.00

   MANGANESE (in mg) PHOSPHORUS (in mg) POTASSIUM (in mg) SELENIUM (in mg)  \
0                  0                  0               0.0                0
1                  0                  0               0.0                0
2                  0                  0             223.0                0
3                  0                  0               0.0                0
4                  0                  0               0.0                0
5                  0                  0               0.0                0
6                  -                  -             421.0                -
7                  0                  0               0.0                0
8                  0                  0               0.0                0
9                  0                  0               0.0                0
10                 0                  0               0.0                0
11                 0                  0             358.0                0
12                 0                  0               0.0                0
13                 0                  0               0.0                0
14                 0                  0               0.0                0
15                 0                  0               0.0                0
16                 0                  0               0.0                0
17                 0                  0               0.0                0
18                 0               14.5             263.9                0
19                 0               23.1             156.0                0
20             0.001                0.2               0.5             0.02
21             1.544                438            1375.0           0.0091
22                 0                  0             116.0                0
23                 0                  0              87.0                0
24                 0                  0               0.0                0

   ZINC (in mg) SERVING_SIZE (in ml)
0             0                    0
1             0                    0
2             0                    0
3             0                    0
4             0                    0
5             0                    0
6             -                    0
7             0                    0
8             0                    0
9             0                    0
10            0                    0
11            0                    0
12            0                    0
13            0                    0
14            0                    0
15            0                    0
16            0                    0
17            0                    0
18            0                    0
19            0                    0
20            0                    0
21         6.11                    0
22            0               240 ML
23            0                240ML
24            0                 15ML

[25 rows x 37 columns]

In [ ]:
#remove ml
df1['SERVING_SIZE (in ml)']=df1['SERVING_SIZE (in ml)'].apply(lambda x: str(x).replace('ML','') if isinstance(x,str) else x)
print(df1.head(25))

                 FOOD_ITEM         FOOD_GROUP  SERVING_SIZE (in g)  \
0                     FIGS  DRY FRUITS, SEEDS                 50.0
1                CURRANTS   DRY FRUITS, SEEDS                 50.0
2                 CHICKEN                MEAT                100.0
3            GOJI BERRIES   DRY FRUITS, SEEDS                 80.0
4                 COCONUT   DRY FRUITS, SEEDS                 80.0
5   DATES (MEDJOOL, DRIED)  DRY FRUITS, SEEDS                 50.0
6                  MUTTON                MEAT                100.0
7                OLIVE OIL               OILS                 14.0
8              COCONUT OIL               OILS                 14.0
9               CANOLA OIL               OILS                 14.0
10                   APPLE             FRUITS                182.0
11                  BANANA             FRUITS                100.0
12           SUNFLOWER OIL               OILS                 14.0
13              WATERMELON             FRUITS                154.0
14             SOYBEAN OIL               OILS                 14.0
15              STRAWBERRY             FRUITS                 72.0
16                    PEAR             FRUITS                178.0
17                   PEACH             FRUITS                175.0
18                  PAPAYA             FRUITS                152.0
19                   MANGO             FRUITS                100.0
20             AVOCADO OIL               OILS                 14.0
21               ASH GOURD         VEGETABLES                100.0
22            BLACK COFFEE          BEVERAGES                  NaN
23               BLACK TEA          BEVERAGES                  NaN
24           COFFEE OR TEA          BEVERAGES                  NaN

   CALORIC_VALUE (in g) PROTEIN (in g)  FAT (in g)  SATURATED_FAT (in g)  \
0                   249            3.3         0.9                   0.0
1                   283            3.8         0.4                   0.0
2                   239             27        14.0                   3.8
3                   349           14.3         0.4                   0.0
4                   660            6.9        64.5                   0.0
5                   299            3.1         0.5                   0.0
6                   143             26         3.5                   1.2
7                   119              0        14.0                   2.0
8                   121              0        13.5                  11.2
9                   124              0        14.0                   1.0
10                   95              0         0.0                   0.0
11                   89            1.1         0.3                   0.1
12                  120              0        14.0                   1.5
13                   46              1         0.0                   0.0
14                  120              0        14.0                   2.0
15                   25              0         0.0                   0.0
16                  103              1         0.0                   0.0
17                   68              2         0.0                   0.0
18                   60              1         0.0                   0.0
19                   65            0.5         0.3                   0.0
20                  124              0        14.0                   2.0
21                  340             24         2.0                   0.0
22                    2            0.3         0.0                   0.0
23                    2              0         0.0                   0.0
24                    9            0.5         0.5                   0.3

   MONOUNSATURATED_FAT (in g) POLYUNSATURATED_FAT (in g) CARBOHYDRATES (in g)  \
0                           0                          0                 63.9
1                           0                          0                 69.2
2                           0                          0                    0
3                           0                          0                 69.7
4                           0                          0                 23.7
5                           0                          0                 79.2
6                           -                          -                    0
7                          10                        1.2                    0
8                         0.8                        0.2                    0
9                           9                          4                    0
10                          0                          0                   25
11                          0                          0                   23
12                        2.7                        9.4                    0
13                          0                          0                   12
14                          3                          8                    0
15                          0                          0                    6
16                          0                          0                   28
17                          0                          0                   17
18                          0                          0                   15
19                          0                          0                   17
20                         10                          2                    0
21                          -                          -                   60
22                          0                          0                    0
23                          0                          0                  0.7
24                          0                          0                  0.7

    ...  CALCIUM (in mg)  COPPER (in mg)  IRON (in mg)  MAGNESIUM (in mg)  \
0   ...             0.00           0.000          0.00               0.00
1   ...             0.00           0.000          0.00               0.00
2   ...             1.00           0.000          7.00               5.00
3   ...             0.00           0.000          0.00               0.00
4   ...             0.00           0.000          0.00               0.00
5   ...             0.00           0.000          0.00               0.00
6   ...             0.00           0.000          6.00               7.00
7   ...             1.00           0.000          0.10               0.00
8   ...             0.00           0.000          0.10               0.00
9   ...             0.00           0.000          0.10               0.00
10  ...          1820.00           0.000          0.00               0.00
11  ...             0.00           0.000       1000.00            6000.00
12  ...             0.00           0.000          0.10               0.00
13  ...          1540.00           0.000       3080.00               0.00
14  ...             0.00           0.000          0.10               0.00
15  ...             0.00           0.000          0.00               0.00
16  ...          3560.00           0.000       3560.00               0.00
17  ...          1750.00           0.000       3500.00               0.00
18  ...            29.00           0.000          0.36               0.00
19  ...            18.20           0.100          0.26               0.00
20  ...             0.02           0.030          0.10               0.09
21  ...            85.00           1.059          9.95             333.00
22  ...             4.70           0.000          0.00               0.00
23  ...             7.00           0.000          0.00               0.00
24  ...            17.00           0.000          0.00               0.00

   MANGANESE (in mg) PHOSPHORUS (in mg) POTASSIUM (in mg) SELENIUM (in mg)  \
0                  0                  0               0.0                0
1                  0                  0               0.0                0
2                  0                  0             223.0                0
3                  0                  0               0.0                0
4                  0                  0               0.0                0
5                  0                  0               0.0                0
6                  -                  -             421.0                -
7                  0                  0               0.0                0
8                  0                  0               0.0                0
9                  0                  0               0.0                0
10                 0                  0               0.0                0
11                 0                  0             358.0                0
12                 0                  0               0.0                0
13                 0                  0               0.0                0
14                 0                  0               0.0                0
15                 0                  0               0.0                0
16                 0                  0               0.0                0
17                 0                  0               0.0                0
18                 0               14.5             263.9                0
19                 0               23.1             156.0                0
20             0.001                0.2               0.5             0.02
21             1.544                438            1375.0           0.0091
22                 0                  0             116.0                0
23                 0                  0              87.0                0
24                 0                  0               0.0                0

   ZINC (in mg) SERVING_SIZE (in ml)
0             0                    0
1             0                    0
2             0                    0
3             0                    0
4             0                    0
5             0                    0
6             -                    0
7             0                    0
8             0                    0
9             0                    0
10            0                    0
11            0                    0
12            0                    0
13            0                    0
14            0                    0
15            0                    0
16            0                    0
17            0                    0
18            0                    0
19            0                    0
20            0                    0
21         6.11                    0
22            0                 240
23            0                  240
24            0                   15

[25 rows x 37 columns]

In [ ]:
df1['SERVING_SIZE (in ml)']=pd.to_numeric(df1['SERVING_SIZE (in ml)'],errors='coerce')
print(df1.head(25))

                 FOOD_ITEM         FOOD_GROUP  SERVING_SIZE (in g)  \
0                     FIGS  DRY FRUITS, SEEDS                 50.0
1                CURRANTS   DRY FRUITS, SEEDS                 50.0
2                 CHICKEN                MEAT                100.0
3            GOJI BERRIES   DRY FRUITS, SEEDS                 80.0
4                 COCONUT   DRY FRUITS, SEEDS                 80.0
5   DATES (MEDJOOL, DRIED)  DRY FRUITS, SEEDS                 50.0
6                  MUTTON                MEAT                100.0
7                OLIVE OIL               OILS                 14.0
8              COCONUT OIL               OILS                 14.0
9               CANOLA OIL               OILS                 14.0
10                   APPLE             FRUITS                182.0
11                  BANANA             FRUITS                100.0
12           SUNFLOWER OIL               OILS                 14.0
13              WATERMELON             FRUITS                154.0
14             SOYBEAN OIL               OILS                 14.0
15              STRAWBERRY             FRUITS                 72.0
16                    PEAR             FRUITS                178.0
17                   PEACH             FRUITS                175.0
18                  PAPAYA             FRUITS                152.0
19                   MANGO             FRUITS                100.0
20             AVOCADO OIL               OILS                 14.0
21               ASH GOURD         VEGETABLES                100.0
22            BLACK COFFEE          BEVERAGES                  NaN
23               BLACK TEA          BEVERAGES                  NaN
24           COFFEE OR TEA          BEVERAGES                  NaN

   CALORIC_VALUE (in g) PROTEIN (in g)  FAT (in g)  SATURATED_FAT (in g)  \
0                   249            3.3         0.9                   0.0
1                   283            3.8         0.4                   0.0
2                   239             27        14.0                   3.8
3                   349           14.3         0.4                   0.0
4                   660            6.9        64.5                   0.0
5                   299            3.1         0.5                   0.0
6                   143             26         3.5                   1.2
7                   119              0        14.0                   2.0
8                   121              0        13.5                  11.2
9                   124              0        14.0                   1.0
10                   95              0         0.0                   0.0
11                   89            1.1         0.3                   0.1
12                  120              0        14.0                   1.5
13                   46              1         0.0                   0.0
14                  120              0        14.0                   2.0
15                   25              0         0.0                   0.0
16                  103              1         0.0                   0.0
17                   68              2         0.0                   0.0
18                   60              1         0.0                   0.0
19                   65            0.5         0.3                   0.0
20                  124              0        14.0                   2.0
21                  340             24         2.0                   0.0
22                    2            0.3         0.0                   0.0
23                    2              0         0.0                   0.0
24                    9            0.5         0.5                   0.3

   MONOUNSATURATED_FAT (in g) POLYUNSATURATED_FAT (in g) CARBOHYDRATES (in g)  \
0                           0                          0                 63.9
1                           0                          0                 69.2
2                           0                          0                    0
3                           0                          0                 69.7
4                           0                          0                 23.7
5                           0                          0                 79.2
6                           -                          -                    0
7                          10                        1.2                    0
8                         0.8                        0.2                    0
9                           9                          4                    0
10                          0                          0                   25
11                          0                          0                   23
12                        2.7                        9.4                    0
13                          0                          0                   12
14                          3                          8                    0
15                          0                          0                    6
16                          0                          0                   28
17                          0                          0                   17
18                          0                          0                   15
19                          0                          0                   17
20                         10                          2                    0
21                          -                          -                   60
22                          0                          0                    0
23                          0                          0                  0.7
24                          0                          0                  0.7

    ...  CALCIUM (in mg)  COPPER (in mg)  IRON (in mg)  MAGNESIUM (in mg)  \
0   ...             0.00           0.000          0.00               0.00
1   ...             0.00           0.000          0.00               0.00
2   ...             1.00           0.000          7.00               5.00
3   ...             0.00           0.000          0.00               0.00
4   ...             0.00           0.000          0.00               0.00
5   ...             0.00           0.000          0.00               0.00
6   ...             0.00           0.000          6.00               7.00
7   ...             1.00           0.000          0.10               0.00
8   ...             0.00           0.000          0.10               0.00
9   ...             0.00           0.000          0.10               0.00
10  ...          1820.00           0.000          0.00               0.00
11  ...             0.00           0.000       1000.00            6000.00
12  ...             0.00           0.000          0.10               0.00
13  ...          1540.00           0.000       3080.00               0.00
14  ...             0.00           0.000          0.10               0.00
15  ...             0.00           0.000          0.00               0.00
16  ...          3560.00           0.000       3560.00               0.00
17  ...          1750.00           0.000       3500.00               0.00
18  ...            29.00           0.000          0.36               0.00
19  ...            18.20           0.100          0.26               0.00
20  ...             0.02           0.030          0.10               0.09
21  ...            85.00           1.059          9.95             333.00
22  ...             4.70           0.000          0.00               0.00
23  ...             7.00           0.000          0.00               0.00
24  ...            17.00           0.000          0.00               0.00

   MANGANESE (in mg) PHOSPHORUS (in mg) POTASSIUM (in mg) SELENIUM (in mg)  \
0                  0                  0               0.0                0
1                  0                  0               0.0                0
2                  0                  0             223.0                0
3                  0                  0               0.0                0
4                  0                  0               0.0                0
5                  0                  0               0.0                0
6                  -                  -             421.0                -
7                  0                  0               0.0                0
8                  0                  0               0.0                0
9                  0                  0               0.0                0
10                 0                  0               0.0                0
11                 0                  0             358.0                0
12                 0                  0               0.0                0
13                 0                  0               0.0                0
14                 0                  0               0.0                0
15                 0                  0               0.0                0
16                 0                  0               0.0                0
17                 0                  0               0.0                0
18                 0               14.5             263.9                0
19                 0               23.1             156.0                0
20             0.001                0.2               0.5             0.02
21             1.544                438            1375.0           0.0091
22                 0                  0             116.0                0
23                 0                  0              87.0                0
24                 0                  0               0.0                0

   ZINC (in mg) SERVING_SIZE (in ml)
0             0                    0
1             0                    0
2             0                    0
3             0                    0
4             0                    0
5             0                    0
6             -                    0
7             0                    0
8             0                    0
9             0                    0
10            0                    0
11            0                    0
12            0                    0
13            0                    0
14            0                    0
15            0                    0
16            0                    0
17            0                    0
18            0                    0
19            0                    0
20            0                    0
21         6.11                    0
22            0                  240
23            0                  240
24            0                   15

[25 rows x 37 columns]

In [ ]:
df1['SERVING_SIZE (in g)']=df1['SERVING_SIZE (in g)'].fillna(0)
print(df1.head(25))

                 FOOD_ITEM         FOOD_GROUP  SERVING_SIZE (in g)  \
0                     FIGS  DRY FRUITS, SEEDS                 50.0
1                CURRANTS   DRY FRUITS, SEEDS                 50.0
2                 CHICKEN                MEAT                100.0
3            GOJI BERRIES   DRY FRUITS, SEEDS                 80.0
4                 COCONUT   DRY FRUITS, SEEDS                 80.0
5   DATES (MEDJOOL, DRIED)  DRY FRUITS, SEEDS                 50.0
6                  MUTTON                MEAT                100.0
7                OLIVE OIL               OILS                 14.0
8              COCONUT OIL               OILS                 14.0
9               CANOLA OIL               OILS                 14.0
10                   APPLE             FRUITS                182.0
11                  BANANA             FRUITS                100.0
12           SUNFLOWER OIL               OILS                 14.0
13              WATERMELON             FRUITS                154.0
14             SOYBEAN OIL               OILS                 14.0
15              STRAWBERRY             FRUITS                 72.0
16                    PEAR             FRUITS                178.0
17                   PEACH             FRUITS                175.0
18                  PAPAYA             FRUITS                152.0
19                   MANGO             FRUITS                100.0
20             AVOCADO OIL               OILS                 14.0
21               ASH GOURD         VEGETABLES                100.0
22            BLACK COFFEE          BEVERAGES                  0.0
23               BLACK TEA          BEVERAGES                  0.0
24           COFFEE OR TEA          BEVERAGES                  0.0

   CALORIC_VALUE (in g) PROTEIN (in g)  FAT (in g)  SATURATED_FAT (in g)  \
0                   249            3.3         0.9                   0.0
1                   283            3.8         0.4                   0.0
2                   239             27        14.0                   3.8
3                   349           14.3         0.4                   0.0
4                   660            6.9        64.5                   0.0
5                   299            3.1         0.5                   0.0
6                   143             26         3.5                   1.2
7                   119              0        14.0                   2.0
8                   121              0        13.5                  11.2
9                   124              0        14.0                   1.0
10                   95              0         0.0                   0.0
11                   89            1.1         0.3                   0.1
12                  120              0        14.0                   1.5
13                   46              1         0.0                   0.0
14                  120              0        14.0                   2.0
15                   25              0         0.0                   0.0
16                  103              1         0.0                   0.0
17                   68              2         0.0                   0.0
18                   60              1         0.0                   0.0
19                   65            0.5         0.3                   0.0
20                  124              0        14.0                   2.0
21                  340             24         2.0                   0.0
22                    2            0.3         0.0                   0.0
23                    2              0         0.0                   0.0
24                    9            0.5         0.5                   0.3

   MONOUNSATURATED_FAT (in g) POLYUNSATURATED_FAT (in g) CARBOHYDRATES (in g)  \
0                           0                          0                 63.9
1                           0                          0                 69.2
2                           0                          0                    0
3                           0                          0                 69.7
4                           0                          0                 23.7
5                           0                          0                 79.2
6                           -                          -                    0
7                          10                        1.2                    0
8                         0.8                        0.2                    0
9                           9                          4                    0
10                          0                          0                   25
11                          0                          0                   23
12                        2.7                        9.4                    0
13                          0                          0                   12
14                          3                          8                    0
15                          0                          0                    6
16                          0                          0                   28
17                          0                          0                   17
18                          0                          0                   15
19                          0                          0                   17
20                         10                          2                    0
21                          -                          -                   60
22                          0                          0                    0
23                          0                          0                  0.7
24                          0                          0                  0.7

    ...  CALCIUM (in mg)  COPPER (in mg)  IRON (in mg)  MAGNESIUM (in mg)  \
0   ...             0.00           0.000          0.00               0.00
1   ...             0.00           0.000          0.00               0.00
2   ...             1.00           0.000          7.00               5.00
3   ...             0.00           0.000          0.00               0.00
4   ...             0.00           0.000          0.00               0.00
5   ...             0.00           0.000          0.00               0.00
6   ...             0.00           0.000          6.00               7.00
7   ...             1.00           0.000          0.10               0.00
8   ...             0.00           0.000          0.10               0.00
9   ...             0.00           0.000          0.10               0.00
10  ...          1820.00           0.000          0.00               0.00
11  ...             0.00           0.000       1000.00            6000.00
12  ...             0.00           0.000          0.10               0.00
13  ...          1540.00           0.000       3080.00               0.00
14  ...             0.00           0.000          0.10               0.00
15  ...             0.00           0.000          0.00               0.00
16  ...          3560.00           0.000       3560.00               0.00
17  ...          1750.00           0.000       3500.00               0.00
18  ...            29.00           0.000          0.36               0.00
19  ...            18.20           0.100          0.26               0.00
20  ...             0.02           0.030          0.10               0.09
21  ...            85.00           1.059          9.95             333.00
22  ...             4.70           0.000          0.00               0.00
23  ...             7.00           0.000          0.00               0.00
24  ...            17.00           0.000          0.00               0.00

   MANGANESE (in mg) PHOSPHORUS (in mg) POTASSIUM (in mg) SELENIUM (in mg)  \
0                  0                  0               0.0                0
1                  0                  0               0.0                0
2                  0                  0             223.0                0
3                  0                  0               0.0                0
4                  0                  0               0.0                0
5                  0                  0               0.0                0
6                  -                  -             421.0                -
7                  0                  0               0.0                0
8                  0                  0               0.0                0
9                  0                  0               0.0                0
10                 0                  0               0.0                0
11                 0                  0             358.0                0
12                 0                  0               0.0                0
13                 0                  0               0.0                0
14                 0                  0               0.0                0
15                 0                  0               0.0                0
16                 0                  0               0.0                0
17                 0                  0               0.0                0
18                 0               14.5             263.9                0
19                 0               23.1             156.0                0
20             0.001                0.2               0.5             0.02
21             1.544                438            1375.0           0.0091
22                 0                  0             116.0                0
23                 0                  0              87.0                0
24                 0                  0               0.0                0

   ZINC (in mg) SERVING_SIZE (in ml)
0             0                    0
1             0                    0
2             0                    0
3             0                    0
4             0                    0
5             0                    0
6             -                    0
7             0                    0
8             0                    0
9             0                    0
10            0                    0
11            0                    0
12            0                    0
13            0                    0
14            0                    0
15            0                    0
16            0                    0
17            0                    0
18            0                    0
19            0                    0
20            0                    0
21         6.11                    0
22            0                  240
23            0                  240
24            0                   15

[25 rows x 37 columns]

In [ ]:
df1.to_csv('projectfile.csv',index=False)
df=pd.read_csv('projectfile.csv')
df.head()

,FOOD_ITEM,FOOD_GROUP,SERVING_SIZE (in g),CALORIC_VALUE (in g),PROTEIN (in g),FAT (in g),SATURATED_FAT (in g),MONOUNSATURATED_FAT (in g),POLYUNSATURATED_FAT (in g),CARBOHYDRATES (in g),...,CALCIUM (in mg),COPPER (in mg),IRON (in mg),MAGNESIUM (in mg),MANGANESE (in mg),PHOSPHORUS (in mg),POTASSIUM (in mg),SELENIUM (in mg),ZINC (in mg),SERVING_SIZE (in ml)
0,FIGS,"DRY FRUITS, SEEDS",50.0,249,3.3,0.9,0.0,0,0,63.9,...,0.0,0.0,0.0,0.0,0,0,0.0,0,0,0
1,CURRANTS,"DRY FRUITS, SEEDS",50.0,283,3.8,0.4,0.0,0,0,69.2,...,0.0,0.0,0.0,0.0,0,0,0.0,0,0,0
2,CHICKEN,MEAT,100.0,239,27,14.0,3.8,0,0,0,...,1.0,0.0,7.0,5.0,0,0,223.0,0,0,0
3,GOJI BERRIES,"DRY FRUITS, SEEDS",80.0,349,14.3,0.4,0.0,0,0,69.7,...,0.0,0.0,0.0,0.0,0,0,0.0,0,0,0
4,COCONUT,"DRY FRUITS, SEEDS",80.0,660,6.9,64.5,0.0,0,0,23.7,...,0.0,0.0,0.0,0.0,0,0,0.0,0,0,0

In [ ]:
# List of columns to convert
columns_to_convert = [
    'CALORIC_VALUE (in g)',
    'PROTEIN (in g)',
    'MONOUNSATURATED_FAT (in g)',
    'POLYUNSATURATED_FAT (in g)',
    'CARBOHYDRATES (in g)',
    'VITAMIN A (in %)',
    'VITAMIN B1 (in %)',
    'VITAMIN B2 (in %)',
    'VITAMIN B3 (in %)',
    'VITAMIN B5 (in %)',
    'VITAMIN B6 (in %)',
    'VITAMIN B11 (in %)',
    'VITAMIN B12 (in %)',
    'VITAMIN E (in %)',
    'VITAMIN K (in %)',
    'WATER (in g)',
    'MAGNESIUM (in mg)',
     'MANGANESE (in mg)',
    'PHOSPHORUS (in mg)',
    'SELENIUM (in mg)',
    'ZINC (in mg)'
]

# Convert each column to numeric type
for col in columns_to_convert:
    df[col] = pd.to_numeric(df[col], errors='coerce')  # Use errors='coerce' to handle non-numeric values

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 37 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   FOOD_ITEM                   300 non-null    object
 1   FOOD_GROUP                  300 non-null    object
 2   SERVING_SIZE (in g)         300 non-null    float64
 3   CALORIC_VALUE (in g)        299 non-null    float64
 4   PROTEIN (in g)              299 non-null    float64
 5   FAT (in g)                  300 non-null    float64
 6   SATURATED_FAT (in g)        300 non-null    float64
 7   MONOUNSATURATED_FAT (in g)  298 non-null    float64
 8   POLYUNSATURATED_FAT (in g)  298 non-null    float64
 9   CARBOHYDRATES (in g)        299 non-null    float64
 10  DIETARY_FIBER (in g)        300 non-null    float64
 11  SUGARS (in g)               300 non-null    float64
 12  SODIUM (in g)               300 non-null    float64
 13  CHOLESTROL (in mg)          300 non-null    float64
 14  VITAMIN A (in %)            299 non-null    float64
 15  VITAMIN B1 (in %)           299 non-null    float64
 16  VITAMIN B2 (in %)           299 non-null    float64
 17  VITAMIN B3 (in %)           299 non-null    float64
 18  VITAMIN B5 (in %)           299 non-null    float64
 19  VITAMIN B6 (in %)           299 non-null    float64
 20  VITAMIN B11 (in %)          299 non-null    float64
 21  VITAMIN B12 (in %)          299 non-null    float64
 22  VITAMIN C (in %)            300 non-null    float64
 23  VITAMIN D (in %)            300 non-null    float64
 24  VITAMIN E (in %)            297 non-null    float64
 25  VITAMIN K (in %)            297 non-null    float64
 26  WATER (in g)                298 non-null    float64
 27  CALCIUM (in mg)             300 non-null    float64
 28  COPPER (in mg)              300 non-null    float64
 29  IRON (in mg)                300 non-null    float64
 30  MAGNESIUM (in mg)           300 non-null    float64
 31  MANGANESE (in mg)           299 non-null    float64
 32  PHOSPHORUS (in mg)          299 non-null    float64
 33  POTASSIUM (in mg)           300 non-null    float64
 34  SELENIUM (in mg)            299 non-null    float64
 35  ZINC (in mg)                299 non-null    float64
 36  SERVING_SIZE (in ml)        300 non-null    int64
dtypes: float64(34), int64(1), object(2)
memory usage: 86.8+ KB